// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=mocks/mock_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	domain "github.com/solympe/leetcode-tg-notifier/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockbotAPI is a mock of botAPI interface.
type MockbotAPI struct {
	ctrl     *gomock.Controller
	recorder *MockbotAPIMockRecorder
	isgomock struct{}
}

// MockbotAPIMockRecorder is the mock recorder for MockbotAPI.
type MockbotAPIMockRecorder struct {
	mock *MockbotAPI
}

// NewMockbotAPI creates a new mock instance.
func NewMockbotAPI(ctrl *gomock.Controller) *MockbotAPI {
	mock := &MockbotAPI{ctrl: ctrl}
	mock.recorder = &MockbotAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbotAPI) EXPECT() *MockbotAPIMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockbotAPI) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", c)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockbotAPIMockRecorder) Request(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockbotAPI)(nil).Request), c)
}

// Send mocks base method.
func (m *MockbotAPI) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", c)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockbotAPIMockRecorder) Send(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockbotAPI)(nil).Send), c)
}

// Mockservice is a mock of service interface.
type Mockservice struct {
	ctrl     *gomock.Controller
	recorder *MockserviceMockRecorder
	isgomock struct{}
}

// MockserviceMockRecorder is the mock recorder for Mockservice.
type MockserviceMockRecorder struct {
	mock *Mockservice
}

// NewMockservice creates a new mock instance.
func NewMockservice(ctrl *gomock.Controller) *Mockservice {
	mock := &Mockservice{ctrl: ctrl}
	mock.recorder = &MockserviceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockservice) EXPECT() *MockserviceMockRecorder {
	return m.recorder
}

// SendDaily mocks base method.
func (m *Mockservice) SendDaily(ctx context.Context, chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendDaily", ctx, chatID)
}

// SendDaily indicates an expected call of SendDaily.
func (mr *MockserviceMockRecorder) SendDaily(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDaily", reflect.TypeOf((*Mockservice)(nil).SendDaily), ctx, chatID)
}

// SendToday mocks base method.
func (m *Mockservice) SendToday(ctx context.Context, chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SendToday", ctx, chatID)
}

// SendToday indicates an expected call of SendToday.
func (mr *MockserviceMockRecorder) SendToday(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToday", reflect.TypeOf((*Mockservice)(nil).SendToday), ctx, chatID)
}

// SetDifficulties mocks base method.
func (m *Mockservice) SetDifficulties(ctx context.Context, chatID int64, difficulties []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDifficulties", ctx, chatID, difficulties)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDifficulties indicates an expected call of SetDifficulties.
func (mr *MockserviceMockRecorder) SetDifficulties(ctx, chatID, difficulties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDifficulties", reflect.TypeOf((*Mockservice)(nil).SetDifficulties), ctx, chatID, difficulties)
}

// Solve mocks base method.
func (m *Mockservice) Solve(ctx context.Context, chatID, userID int64, name string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Solve", ctx, chatID, userID, name)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Solve indicates an expected call of Solve.
func (mr *MockserviceMockRecorder) Solve(ctx, chatID, userID, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Solve", reflect.TypeOf((*Mockservice)(nil).Solve), ctx, chatID, userID, name)
}

// Subscribe mocks base method.
func (m *Mockservice) Subscribe(ctx context.Context, chatID int64, notifyTime, timezone string, difficulties []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, chatID, notifyTime, timezone, difficulties)
	ret0, _ := ret[0].(error)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockserviceMockRecorder) Subscribe(ctx, chatID, notifyTime, timezone, difficulties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*Mockservice)(nil).Subscribe), ctx, chatID, notifyTime, timezone, difficulties)
}

// Subscription mocks base method.
func (m *Mockservice) Subscription(ctx context.Context, chatID int64) (domain.Chat, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscription", ctx, chatID)
	ret0, _ := ret[0].(domain.Chat)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Subscription indicates an expected call of Subscription.
func (mr *MockserviceMockRecorder) Subscription(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscription", reflect.TypeOf((*Mockservice)(nil).Subscription), ctx, chatID)
}

// Unsubscribe mocks base method.
func (m *Mockservice) Unsubscribe(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockserviceMockRecorder) Unsubscribe(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*Mockservice)(nil).Unsubscribe), ctx, chatID)
}
