// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=mocks/mock_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	gomock "go.uber.org/mock/gomock"
)

// MockbotAPI is a mock of botAPI interface.
type MockbotAPI struct {
	ctrl     *gomock.Controller
	recorder *MockbotAPIMockRecorder
	isgomock struct{}
}

// MockbotAPIMockRecorder is the mock recorder for MockbotAPI.
type MockbotAPIMockRecorder struct {
	mock *MockbotAPI
}

// NewMockbotAPI creates a new mock instance.
func NewMockbotAPI(ctrl *gomock.Controller) *MockbotAPI {
	mock := &MockbotAPI{ctrl: ctrl}
	mock.recorder = &MockbotAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbotAPI) EXPECT() *MockbotAPIMockRecorder {
	return m.recorder
}

// Request mocks base method.
func (m *MockbotAPI) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", c)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockbotAPIMockRecorder) Request(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockbotAPI)(nil).Request), c)
}

// Send mocks base method.
func (m *MockbotAPI) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", c)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MockbotAPIMockRecorder) Send(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockbotAPI)(nil).Send), c)
}
