// Code generated by MockGen. DO NOT EDIT.
// Source: bot.go
//
// Generated by this command:
//
//	mockgen -source=bot.go -destination=mocks/mock_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	leetcode "github.com/solympe/leetcode-tg-notifier/internal/leetcode"
	storage "github.com/solympe/leetcode-tg-notifier/internal/storage"
	gomock "go.uber.org/mock/gomock"
)

// MocktelegramSender is a mock of telegramSender interface.
type MocktelegramSender struct {
	ctrl     *gomock.Controller
	recorder *MocktelegramSenderMockRecorder
	isgomock struct{}
}

// MocktelegramSenderMockRecorder is the mock recorder for MocktelegramSender.
type MocktelegramSenderMockRecorder struct {
	mock *MocktelegramSender
}

// NewMocktelegramSender creates a new mock instance.
func NewMocktelegramSender(ctrl *gomock.Controller) *MocktelegramSender {
	mock := &MocktelegramSender{ctrl: ctrl}
	mock.recorder = &MocktelegramSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktelegramSender) EXPECT() *MocktelegramSenderMockRecorder {
	return m.recorder
}

// GetUpdatesChan mocks base method.
func (m *MocktelegramSender) GetUpdatesChan(config tgbotapi.UpdateConfig) tgbotapi.UpdatesChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUpdatesChan", config)
	ret0, _ := ret[0].(tgbotapi.UpdatesChannel)
	return ret0
}

// GetUpdatesChan indicates an expected call of GetUpdatesChan.
func (mr *MocktelegramSenderMockRecorder) GetUpdatesChan(config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUpdatesChan", reflect.TypeOf((*MocktelegramSender)(nil).GetUpdatesChan), config)
}

// Request mocks base method.
func (m *MocktelegramSender) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", c)
	ret0, _ := ret[0].(*tgbotapi.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MocktelegramSenderMockRecorder) Request(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MocktelegramSender)(nil).Request), c)
}

// Send mocks base method.
func (m *MocktelegramSender) Send(c tgbotapi.Chattable) (tgbotapi.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", c)
	ret0, _ := ret[0].(tgbotapi.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Send indicates an expected call of Send.
func (mr *MocktelegramSenderMockRecorder) Send(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MocktelegramSender)(nil).Send), c)
}

// MockchatStore is a mock of chatStore interface.
type MockchatStore struct {
	ctrl     *gomock.Controller
	recorder *MockchatStoreMockRecorder
	isgomock struct{}
}

// MockchatStoreMockRecorder is the mock recorder for MockchatStore.
type MockchatStoreMockRecorder struct {
	mock *MockchatStore
}

// NewMockchatStore creates a new mock instance.
func NewMockchatStore(ctrl *gomock.Controller) *MockchatStore {
	mock := &MockchatStore{ctrl: ctrl}
	mock.recorder = &MockchatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatStore) EXPECT() *MockchatStoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockchatStore) Delete(chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockchatStoreMockRecorder) Delete(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockchatStore)(nil).Delete), chatID)
}

// Get mocks base method.
func (m *MockchatStore) Get(chatID int64) (storage.ChatConfig, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", chatID)
	ret0, _ := ret[0].(storage.ChatConfig)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockchatStoreMockRecorder) Get(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockchatStore)(nil).Get), chatID)
}

// Set mocks base method.
func (m *MockchatStore) Set(cfg storage.ChatConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockchatStoreMockRecorder) Set(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockchatStore)(nil).Set), cfg)
}

// MocktaskScheduler is a mock of taskScheduler interface.
type MocktaskScheduler struct {
	ctrl     *gomock.Controller
	recorder *MocktaskSchedulerMockRecorder
	isgomock struct{}
}

// MocktaskSchedulerMockRecorder is the mock recorder for MocktaskScheduler.
type MocktaskSchedulerMockRecorder struct {
	mock *MocktaskScheduler
}

// NewMocktaskScheduler creates a new mock instance.
func NewMocktaskScheduler(ctrl *gomock.Controller) *MocktaskScheduler {
	mock := &MocktaskScheduler{ctrl: ctrl}
	mock.recorder = &MocktaskSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktaskScheduler) EXPECT() *MocktaskSchedulerMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MocktaskScheduler) Remove(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", chatID)
}

// Remove indicates an expected call of Remove.
func (mr *MocktaskSchedulerMockRecorder) Remove(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MocktaskScheduler)(nil).Remove), chatID)
}

// Schedule mocks base method.
func (m *MocktaskScheduler) Schedule(chatID int64, cfg storage.ChatConfig) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", chatID, cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MocktaskSchedulerMockRecorder) Schedule(chatID, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MocktaskScheduler)(nil).Schedule), chatID, cfg)
}

// MocklcFetcher is a mock of lcFetcher interface.
type MocklcFetcher struct {
	ctrl     *gomock.Controller
	recorder *MocklcFetcherMockRecorder
	isgomock struct{}
}

// MocklcFetcherMockRecorder is the mock recorder for MocklcFetcher.
type MocklcFetcherMockRecorder struct {
	mock *MocklcFetcher
}

// NewMocklcFetcher creates a new mock instance.
func NewMocklcFetcher(ctrl *gomock.Controller) *MocklcFetcher {
	mock := &MocklcFetcher{ctrl: ctrl}
	mock.recorder = &MocklcFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklcFetcher) EXPECT() *MocklcFetcherMockRecorder {
	return m.recorder
}

// FetchDaily mocks base method.
func (m *MocklcFetcher) FetchDaily() (*leetcode.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDaily")
	ret0, _ := ret[0].(*leetcode.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDaily indicates an expected call of FetchDaily.
func (mr *MocklcFetcherMockRecorder) FetchDaily() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDaily", reflect.TypeOf((*MocklcFetcher)(nil).FetchDaily))
}
