// Code generated by MockGen. DO NOT EDIT.
// Source: deps.go
//
// Generated by this command:
//
//	mockgen -source=deps.go -destination=mocks/mock_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/solympe/leetcode-tg-notifier/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockchatStore is a mock of chatStore interface.
type MockchatStore struct {
	ctrl     *gomock.Controller
	recorder *MockchatStoreMockRecorder
	isgomock struct{}
}

// MockchatStoreMockRecorder is the mock recorder for MockchatStore.
type MockchatStoreMockRecorder struct {
	mock *MockchatStore
}

// NewMockchatStore creates a new mock instance.
func NewMockchatStore(ctrl *gomock.Controller) *MockchatStore {
	mock := &MockchatStore{ctrl: ctrl}
	mock.recorder = &MockchatStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockchatStore) EXPECT() *MockchatStoreMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockchatStore) All(ctx context.Context) ([]domain.Chat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]domain.Chat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockchatStoreMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockchatStore)(nil).All), ctx)
}

// Delete mocks base method.
func (m *MockchatStore) Delete(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockchatStoreMockRecorder) Delete(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockchatStore)(nil).Delete), ctx, chatID)
}

// Get mocks base method.
func (m *MockchatStore) Get(ctx context.Context, chatID int64) (domain.Chat, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, chatID)
	ret0, _ := ret[0].(domain.Chat)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockchatStoreMockRecorder) Get(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockchatStore)(nil).Get), ctx, chatID)
}

// Update mocks base method.
func (m *MockchatStore) Update(ctx context.Context, chatID int64, fn func(*domain.Chat) bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, chatID, fn)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockchatStoreMockRecorder) Update(ctx, chatID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockchatStore)(nil).Update), ctx, chatID, fn)
}

// Upsert mocks base method.
func (m *MockchatStore) Upsert(ctx context.Context, chatID int64, fn func(*domain.Chat)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, chatID, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockchatStoreMockRecorder) Upsert(ctx, chatID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockchatStore)(nil).Upsert), ctx, chatID, fn)
}

// MockproblemSource is a mock of problemSource interface.
type MockproblemSource struct {
	ctrl     *gomock.Controller
	recorder *MockproblemSourceMockRecorder
	isgomock struct{}
}

// MockproblemSourceMockRecorder is the mock recorder for MockproblemSource.
type MockproblemSourceMockRecorder struct {
	mock *MockproblemSource
}

// NewMockproblemSource creates a new mock instance.
func NewMockproblemSource(ctrl *gomock.Controller) *MockproblemSource {
	mock := &MockproblemSource{ctrl: ctrl}
	mock.recorder = &MockproblemSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockproblemSource) EXPECT() *MockproblemSourceMockRecorder {
	return m.recorder
}

// FetchDaily mocks base method.
func (m *MockproblemSource) FetchDaily(ctx context.Context) (domain.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchDaily", ctx)
	ret0, _ := ret[0].(domain.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchDaily indicates an expected call of FetchDaily.
func (mr *MockproblemSourceMockRecorder) FetchDaily(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchDaily", reflect.TypeOf((*MockproblemSource)(nil).FetchDaily), ctx)
}

// FetchRandom mocks base method.
func (m *MockproblemSource) FetchRandom(ctx context.Context, difficulties []string) (domain.Problem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchRandom", ctx, difficulties)
	ret0, _ := ret[0].(domain.Problem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchRandom indicates an expected call of FetchRandom.
func (mr *MockproblemSourceMockRecorder) FetchRandom(ctx, difficulties any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchRandom", reflect.TypeOf((*MockproblemSource)(nil).FetchRandom), ctx, difficulties)
}

// MockdailyScheduler is a mock of dailyScheduler interface.
type MockdailyScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockdailySchedulerMockRecorder
	isgomock struct{}
}

// MockdailySchedulerMockRecorder is the mock recorder for MockdailyScheduler.
type MockdailySchedulerMockRecorder struct {
	mock *MockdailyScheduler
}

// NewMockdailyScheduler creates a new mock instance.
func NewMockdailyScheduler(ctrl *gomock.Controller) *MockdailyScheduler {
	mock := &MockdailyScheduler{ctrl: ctrl}
	mock.recorder = &MockdailySchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdailyScheduler) EXPECT() *MockdailySchedulerMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockdailyScheduler) Remove(chatID int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", chatID)
}

// Remove indicates an expected call of Remove.
func (mr *MockdailySchedulerMockRecorder) Remove(chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockdailyScheduler)(nil).Remove), chatID)
}

// Schedule mocks base method.
func (m *MockdailyScheduler) Schedule(chatID int64, notifyTime, timezone string, job func()) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", chatID, notifyTime, timezone, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockdailySchedulerMockRecorder) Schedule(chatID, notifyTime, timezone, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockdailyScheduler)(nil).Schedule), chatID, notifyTime, timezone, job)
}

// Mockmessenger is a mock of messenger interface.
type Mockmessenger struct {
	ctrl     *gomock.Controller
	recorder *MockmessengerMockRecorder
	isgomock struct{}
}

// MockmessengerMockRecorder is the mock recorder for Mockmessenger.
type MockmessengerMockRecorder struct {
	mock *Mockmessenger
}

// NewMockmessenger creates a new mock instance.
func NewMockmessenger(ctrl *gomock.Controller) *Mockmessenger {
	mock := &Mockmessenger{ctrl: ctrl}
	mock.recorder = &MockmessengerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockmessenger) EXPECT() *MockmessengerMockRecorder {
	return m.recorder
}

// SendFetchFailed mocks base method.
func (m *Mockmessenger) SendFetchFailed(ctx context.Context, chatID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFetchFailed", ctx, chatID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendFetchFailed indicates an expected call of SendFetchFailed.
func (mr *MockmessengerMockRecorder) SendFetchFailed(ctx, chatID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFetchFailed", reflect.TypeOf((*Mockmessenger)(nil).SendFetchFailed), ctx, chatID)
}

// SendProblem mocks base method.
func (m *Mockmessenger) SendProblem(ctx context.Context, chatID int64, p domain.Pick) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendProblem", ctx, chatID, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendProblem indicates an expected call of SendProblem.
func (mr *MockmessengerMockRecorder) SendProblem(ctx, chatID, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendProblem", reflect.TypeOf((*Mockmessenger)(nil).SendProblem), ctx, chatID, p)
}
