// Code generated by MockGen. DO NOT EDIT.
// Source: http.go
//
// Generated by this command:
//
//	mockgen -source=http.go -destination=mocks/mock_deps.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockrandSource is a mock of randSource interface.
type MockrandSource struct {
	ctrl     *gomock.Controller
	recorder *MockrandSourceMockRecorder
	isgomock struct{}
}

// MockrandSourceMockRecorder is the mock recorder for MockrandSource.
type MockrandSourceMockRecorder struct {
	mock *MockrandSource
}

// NewMockrandSource creates a new mock instance.
func NewMockrandSource(ctrl *gomock.Controller) *MockrandSource {
	mock := &MockrandSource{ctrl: ctrl}
	mock.recorder = &MockrandSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrandSource) EXPECT() *MockrandSourceMockRecorder {
	return m.recorder
}

// IntN mocks base method.
func (m *MockrandSource) IntN(n int) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntN", n)
	ret0, _ := ret[0].(int)
	return ret0
}

// IntN indicates an expected call of IntN.
func (mr *MockrandSourceMockRecorder) IntN(n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntN", reflect.TypeOf((*MockrandSource)(nil).IntN), n)
}
